---
infisical_project_id: "286db07f-4dba-4ca9-a515-f017d77b8bf1"
infisical_path: "/hosts/home-server"
discord_client_id: "{{ infisical_secrets.secrets['kvizgame-client-id'] }}"
discord_client_secret: "{{ infisical_secrets.secrets['kvizgame-client-secret'] }}"
discord_proxy_target: "homeserver.zelgray.work"
kvizgame_image_tag: "dev"
kvizgame_image_pull: "never"
...
